### ISSUE TITLE
Show status on a AuthProxyWorkload for each container in the workload

### ISSUE THREAD

**Issue by hessjcg** [GoogleCloudPlatform/cloud-sql-proxy-operator#50] opened 2022-10-10 19:28 UTC
Periodically make the reconcile loop check all AuthProxyWorkload resources and update the status to reflect the current state of the workload's proxy containers.

**Comment by enocom** [comment] 2023-08-16 18:25
Let's consider this a duplicate of https://github.com/GoogleCloudPlatform/cloud-sql-proxy-operator/issues/51.

**Closed by enocom** 2023-08-16 18:25 UTC
Labels: type: feature request, priority: p2, category:proxy-status
