### ISSUE TITLE
Implement authentication using credential file secrets 

### ISSUE THREAD

**Issue by hessjcg** [GoogleCloudPlatform/cloud-sql-proxy-operator#43] opened 2022-10-10 18:54 UTC
GIVEN a customer with a Google Cloud credential JSON file stored in a ConfigMap
WHEN the customer creates an auth proxy workload configured with Credential File set
THEN the proxy will connect to the Google Cloud API using the credential file

This configures the `--credential-file` flag on the proxy container and sets up a volume mount to the Secret.

**Comment by enocom** [comment] 2023-06-29 21:13
Closing as a duplicate of https://github.com/GoogleCloudPlatform/cloud-sql-proxy-operator/issues/384.

**Closed by enocom** 2023-06-29 21:13 UTC
Labels: type: feature request, priority: p2, category: proxy-config
